export default {
  'COMICS_LIST_SET':'COMICS_LIST_SET',
  'STORIES_LIST_SET':'STORIES_LIST_SET',
  'CHARACTER_NAME':'CHARACTER_NAME',
  'CHARACTER_FILTERS_RESET':'CHARACTER_FILTERS_RESET',
  'CHARACTERS_SORT_BY':'CHARACTERS_SORT_BY'
};
