export default {
'CHARACTER_SELECTED_ADD':'CHARACTER_SELECTED_ADD',
'CHARACTER_SELECTED_REMOVE':'CHARACTER_SELECTED_REMOVE',
'COMIC_SELECTED_ADD':'COMIC_SELECTED_ADD',
'COMIC_SELECTED_REMOVE':'COMIC_SELECTED_REMOVE',
'STORY_SELECTED_ADD':'STORY_SELECTED_ADD',
'STORY_SELECTED_REMOVE':'STORY_SELECTED_REMOVE',
'FAVORITES_FLAG_SET':'FAVORITES_FLAG_SET'
};
